/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.expensetracker.ui;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import com.expensetracker.model.Expense;
import com.expensetracker.service.ExpenseService;
import com.expensetracker.dao.ExpenseDAO;
public class MainFrame extends javax.swing.JFrame {

private ExpenseDAO dao = new ExpenseDAO();
private DefaultTableModel tableModel;
    public MainFrame() {
        initComponents();
        dao.createTableIfNotExists();
    tableModel = new DefaultTableModel(
    new String[]{"ID", "Amount", "Category", "Date", "Note"},0
    );
    tableExpenses.setModel(tableModel);

    loadExpenses();
}
private void loadExpenses(){
    tableModel.setRowCount(0);
        double total = 0;
    for (Expense e: dao.getAllExpenses()){
        tableModel.addRow(new Object[]{
            e.getId(),
            e.getAmount(),
            e.getCategory(),
            e.getDate(),
            e.getNote()
            }); 
            total += e.getAmount();
        }
    lblTotal.setText("Total: Rp"+ total);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Note = new javax.swing.JTextField();
        Amount = new javax.swing.JTextField();
        Category = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        Filter = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        SortByAmount = new javax.swing.JButton();
        Apply = new javax.swing.JButton();
        AddExpense = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableExpenses = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Note.setBackground(new java.awt.Color(217, 217, 217));
        Note.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray));
        getContentPane().add(Note, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 240, 30));

        Amount.setBackground(new java.awt.Color(217, 217, 217));
        getContentPane().add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 110, 30));

        Category.setBackground(new java.awt.Color(217, 217, 217));
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });
        getContentPane().add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 110, 30));

        Date.setBackground(new java.awt.Color(217, 217, 217));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 110, 30));

        Filter.setBackground(new java.awt.Color(217, 217, 217));
        Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterActionPerformed(evt);
            }
        });
        getContentPane().add(Filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 110, 40));

        Reset.setBorderPainted(false);
        Reset.setContentAreaFilled(false);
        Reset.setFocusPainted(false);
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 80, 40));

        SortByAmount.setBorderPainted(false);
        SortByAmount.setContentAreaFilled(false);
        SortByAmount.setFocusPainted(false);
        SortByAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortByAmountActionPerformed(evt);
            }
        });
        getContentPane().add(SortByAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 190, 40));

        Apply.setBorderPainted(false);
        Apply.setContentAreaFilled(false);
        Apply.setFocusPainted(false);
        Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyActionPerformed(evt);
            }
        });
        getContentPane().add(Apply, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 90, 40));

        AddExpense.setBorderPainted(false);
        AddExpense.setContentAreaFilled(false);
        AddExpense.setFocusPainted(false);
        AddExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddExpenseActionPerformed(evt);
            }
        });
        getContentPane().add(AddExpense, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 160, 30));

        tableExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Amount", "Category", "Date", "Note"
            }
        ));
        jScrollPane1.setViewportView(tableExpenses);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 840, 300));

        lblTotal.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        lblTotal.setText("Total: Rp 0");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/expensetracker/ui/Slide 4_3 - 1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryActionPerformed

    private void FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilterActionPerformed

    private void AddExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddExpenseActionPerformed
    double amount = Double.parseDouble(Amount.getText());
    String category = Category.getText();
    String date = Date.getText();
    String note = Note.getText();

    dao.addExpense(amount,category,date,note);
    loadExpenses();

    Amount.setText("");
    Category.setText("");
    Date.setText("");
    Note.setText("");
    }//GEN-LAST:event_AddExpenseActionPerformed

    private void ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyActionPerformed
        String keyword = Filter.getText().toLowerCase();
        
        tableModel.setRowCount(0);
        double total = 0;
        for (Expense e : dao.getAllExpenses()){
            String date = e.getDate().toLowerCase().trim();
            String category = e.getCategory().toLowerCase();
            String yearMonth = "";
            if(date.length()>=7){
              yearMonth = date.substring(0,7);
            }
            if(yearMonth.equals(keyword)||category.contains(keyword)|| date.contains(keyword)){
                tableModel.addRow(new Object[]{
                    e.getId(),
                    e.getAmount(),
                    e.getCategory(),
                    e.getDate(),
                    e.getNote()
                });
                total += e.getAmount();
                }
            }
        lblTotal.setText("Total: Rp "+ total);
    }//GEN-LAST:event_ApplyActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        Filter.setText("");
        loadExpenses();
    }//GEN-LAST:event_ResetActionPerformed

    private void SortByAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortByAmountActionPerformed
        List<Expense> expenses = dao.getAllExpenses();
        expenses.sort((e1, e2)-> Double.compare(e1.getAmount(),e2.getAmount()));
        tableModel.setRowCount(0);
        for(Expense e:expenses){
            tableModel.addRow(new Object[]{
                e.getId(),
                e.getAmount(),
                e.getCategory(),
                e.getDate(),
                e.getNote(),
            });
        }
    }//GEN-LAST:event_SortByAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddExpense;
    private javax.swing.JTextField Amount;
    private javax.swing.JButton Apply;
    private javax.swing.JTextField Category;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Filter;
    private javax.swing.JTextField Note;
    private javax.swing.JButton Reset;
    private javax.swing.JButton SortByAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tableExpenses;
    // End of variables declaration//GEN-END:variables
}
